import { Component, computed, input } from '@angular/core';
import type { BriefingResponse } from '@road-travel/sdk';

import { SEVERITY_COLOR, SEVERITY_LABEL, type Severity, formatDistance } from './severity';

/**
 * The AI trip briefing (F-001): the grounded natural-language text plus a structured facts summary.
 * Text is rendered as PLAIN TEXT only (never as HTML) — the backend already grounds + sanitizes it
 * (ADR-0003/0010), and interpolation keeps it inert here. WeatherKit attribution is required on any
 * screen showing weather (App Review).
 */
@Component({
  selector: 'app-briefing-card',
  template: `
    @if (briefing(); as b) {
      <section class="briefing">
        <header>
          <span class="badge" [style.background]="color(b.facts.overall_severity)">
            {{ label(b.facts.overall_severity) }}
          </span>
          <h2>Your briefing</h2>
        </header>

        <!-- plain-text only: bound via interpolation, never innerHTML -->
        <p class="prose">{{ b.text }}</p>

        @if (b.facts.hazards.length) {
          <ul class="hazards">
            @for (h of b.facts.hazards; track $index) {
              <li>
                <span class="hzdot" [style.background]="color(h.severity)"></span>
                <strong>{{ h.type }}</strong> ({{ h.severity }}) —
                {{ dist(h.start_distance_meters) }} to {{ dist(h.end_distance_meters) }}.
                <span class="peak">{{ h.peak_detail }}</span>
              </li>
            }
          </ul>
        } @else {
          <p class="clear-note">No notable hazards along the route.</p>
        }

        <footer>
          <span class="model">generated by {{ b.model }}</span>
          <a
            class="attribution"
            href="https://weatherkit.apple.com/legal-attribution.html"
            target="_blank"
            rel="noopener"
          > Weather</a>
        </footer>
      </section>
    }
  `,
  styles: [
    `
      .briefing {
        border: 1px solid var(--border);
        border-radius: var(--radius);
        padding: 16px 18px;
        background: var(--surface);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
      }
      header {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 8px;
      }
      h2 {
        font-size: 16px;
        margin: 0;
      }
      .badge {
        color: #fff;
        font-size: 11px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.04em;
        padding: 3px 8px;
        border-radius: 999px;
      }
      .prose {
        font-size: 15px;
        line-height: 1.5;
        color: var(--text);
        margin: 0 0 12px;
      }
      .hazards {
        list-style: none;
        padding: 0;
        margin: 0 0 8px;
        display: grid;
        gap: 6px;
      }
      .hazards li {
        font-size: 13px;
        color: var(--text);
      }
      .hzdot {
        display: inline-block;
        width: 9px;
        height: 9px;
        border-radius: 50%;
        margin-right: 6px;
        vertical-align: middle;
      }
      .peak {
        color: var(--muted);
      }
      .clear-note {
        font-size: 13px;
        color: var(--muted);
      }
      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 12px;
        border-top: 1px solid var(--border);
        padding-top: 8px;
      }
      .model {
        font-size: 11px;
        color: var(--muted);
      }
      .attribution {
        font-size: 12px;
        color: var(--muted);
        text-decoration: none;
      }
    `,
  ],
})
export class BriefingCard {
  readonly briefing = input.required<BriefingResponse>();
  readonly units = input<'imperial' | 'metric'>('imperial');

  readonly hazardCount = computed(() => this.briefing().facts.hazards.length);

  color(sev: Severity): string {
    return SEVERITY_COLOR[sev];
  }
  label(sev: Severity): string {
    return SEVERITY_LABEL[sev];
  }
  dist(m: number): string {
    return formatDistance(m, this.units());
  }
}
