import { Component, computed, input, linkedSignal, output } from '@angular/core';
import type { BriefingResponse, ClaimModel } from '@road-travel/sdk';

import { IconComponent } from '../../ui/icon';
import { SEVERITY_COLOR, SEVERITY_LABEL, type Severity, formatDistance } from './severity';

/** The engine's F-001 v2 verdict scale (US-6) — always server-decided, never derived here. */
type Verdict = NonNullable<BriefingResponse['verdict']>;

const VERDICT_LABEL: Record<Verdict, string> = {
  clear: 'Clear',
  caution: 'Caution',
  'consider-waiting': 'Consider waiting',
};

/**
 * The AI trip briefing (F-001): the grounded natural-language text plus a structured facts summary.
 * Text is rendered as PLAIN TEXT only (never as HTML) — the backend already grounds + sanitizes it
 * (ADR-0003/0010), and interpolation keeps it inert here. WeatherKit attribution is required on any
 * screen showing weather (App Review).
 *
 * F-001 v2 progressive disclosure (US-6/7): verdict chip + verdict line → two-sentence `brief`
 * (default) → "More" expands the full `text` → the raw timeline below stays the deepest layer.
 * "Updated" badge when a re-brief's `diff` is material (US-11); subtle stale note when the
 * forecast horizon is long (the prose carries the sentence — the icon is the glanceable signal).
 * US-13: full-prose sentences whose claim has sample refs are tappable — `claimSelect` emits the
 * claim's start sample index for the plan page's existing timeline/map selection sync.
 */
@Component({
  selector: 'app-briefing-card',
  imports: [IconComponent],
  template: `
    @if (briefing(); as b) {
      <section class="briefing">
        <header>
          <span class="ai-disc" aria-hidden="true"><app-icon name="sparkles" [size]="14" /></span>
          @if (!b.verdict) {
            <!-- pre-v2 fallback: severity badge (still server data — never derived client-side) -->
            <span class="badge" [style.background]="color(b.facts.overall_severity)">
              {{ label(b.facts.overall_severity) }}
            </span>
          }
          <h2>Your briefing</h2>
          @if (b.diff?.material) {
            <!-- US-11: the forecast moved materially since the last briefing of this same trip;
                 the prose itself already leads with what changed. -->
            <span class="updated" title="The forecast changed since your last briefing"
              ><app-icon name="refresh-cw" [size]="11" />Updated</span
            >
          }
        </header>

        @if (b.verdict; as v) {
          <div class="verdict-row">
            <span [class]="'chip v-' + v">{{ verdictLabel(v) }}</span>
            @if (b.verdict_line) {
              <span class="verdict-line">{{ b.verdict_line }}</span>
            }
          </div>
        }

        @if (b.stale) {
          <!-- US-11 staleness: glanceable icon + one line; the prose carries the full sentence. -->
          <p class="stale-note">
            <span class="stale-icon" aria-hidden="true"><app-icon name="clock" [size]="12" /></span>
            forecast &gt;12 h out — re-check before leaving
          </p>
        }

        <!-- plain-text only: bound via interpolation, never innerHTML -->
        @if (!expanded() && brief(); as short) {
          <p class="prose">{{ short }}</p>
        } @else if (claims(); as sentences) {
          <p class="prose">
            @for (c of sentences; track $index) {
              <span
                class="claim"
                [class.linked]="c.start_index != null"
                [attr.role]="c.start_index != null ? 'button' : null"
                [attr.tabindex]="c.start_index != null ? 0 : null"
                [attr.title]="c.start_index != null ? 'Show this stretch on the timeline' : null"
                (click)="inspect(c)"
                (keydown.enter)="inspect(c)"
                >{{ c.text }}</span
              >{{ ' ' }}
            }
          </p>
        } @else {
          <p class="prose">{{ b.text }}</p>
        }
        @if (brief()) {
          <button class="more" type="button" (click)="expanded.set(!expanded())">
            {{ expanded() ? 'Less' : 'More' }}
          </button>
        }

        @if (b.facts.hazards.length) {
          <ul class="hazards">
            @for (h of b.facts.hazards; track $index) {
              <li>
                <span class="hzdot" [style.background]="color(h.severity)"></span>
                <strong>{{ h.type }}</strong> ({{ h.severity }}) —
                {{ dist(h.start_distance_meters) }} to {{ dist(h.end_distance_meters) }}.
                <span class="peak">{{ h.peak_detail }}</span>
              </li>
            }
          </ul>
        } @else {
          <p class="clear-note">No notable hazards along the route.</p>
        }

        <footer>
          <span class="model">generated by {{ b.model }}</span>
          <a
            class="attribution"
            href="https://weatherkit.apple.com/legal-attribution.html"
            target="_blank"
            rel="noopener"
          > Weather</a>
        </footer>
      </section>
    }
  `,
  styles: [
    `
      /* Organic 3.1.0: the sage AI card (mock 3a) — no border, sage fill, deep-sage ink. */
      .briefing {
        border-radius: var(--radius-md);
        padding: 16px 18px;
        background: var(--accent-2-100);
        color: var(--accent-2-900);
        box-shadow: var(--shadow-sm);
      }
      header {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 8px;
      }
      .ai-disc {
        flex: 0 0 auto;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 28px;
        height: 28px;
        border-radius: 50%;
        background: var(--accent-2);
        color: #ffffff;
      }
      h2 {
        font-size: 16px;
        margin: 0;
      }
      .badge {
        color: #fff;
        font: 700 11px var(--font-body);
        text-transform: uppercase;
        letter-spacing: 0.04em;
        padding: 3px 10px;
        border-radius: var(--radius-pill);
        white-space: nowrap;
      }
      .updated {
        display: inline-flex;
        align-items: center;
        gap: 4px;
        font: 700 11px var(--font-body);
        background: var(--accent-2-200);
        color: var(--accent-2-800);
        padding: 3px 10px;
        border-radius: var(--radius-pill);
        white-space: nowrap;
      }
      .verdict-row {
        display: flex;
        align-items: baseline;
        gap: 10px;
        margin: 0 0 10px;
      }
      /* Verdict chip — sage all-clear, terracotta ramp for caution / consider-waiting. */
      .chip {
        flex: 0 0 auto;
        color: #fff;
        font: 700 12px var(--font-body);
        letter-spacing: 0.02em;
        padding: 4px 12px;
        border-radius: var(--radius-pill);
        white-space: nowrap;
      }
      .chip.v-clear {
        background: var(--accent-2);
      }
      .chip.v-caution {
        background: var(--accent-400);
      }
      .chip.v-consider-waiting {
        background: var(--accent-600);
      }
      .verdict-line {
        font-family: var(--font-heading);
        font-weight: 400;
        font-size: 19px;
        line-height: 1.2;
      }
      .stale-note {
        display: flex;
        align-items: center;
        gap: 6px;
        font-size: 12px;
        opacity: 0.7;
        margin: 0 0 10px;
      }
      .stale-icon {
        display: inline-flex;
        line-height: 0;
      }
      .prose {
        font-size: 13.5px;
        line-height: 1.45;
        margin: 0 0 6px;
      }
      /* US-13: only sentences WITH a sample-range ref read as tappable. */
      .claim.linked {
        cursor: pointer;
        text-decoration: underline;
        text-decoration-style: dotted;
        text-decoration-color: var(--accent-2-700);
        text-underline-offset: 3px;
        transition: color 150ms ease-out;
      }
      .claim.linked:hover,
      .claim.linked:focus-visible {
        color: var(--accent-2-700);
      }
      .more {
        background: none;
        border: none;
        padding: 0;
        margin: 0 0 12px;
        font: 700 13px var(--font-body);
        color: var(--accent-2-700);
        cursor: pointer;
        transition: color 150ms ease-out;
      }
      .hazards {
        list-style: none;
        padding: 0;
        margin: 0 0 8px;
        display: grid;
        gap: 6px;
      }
      /* Hazard rows: soft terracotta chips on the sage card. */
      .hazards li {
        font-size: 13px;
        background: var(--accent-100);
        border: 1px solid var(--accent-300);
        border-radius: 12px;
        color: var(--accent-800);
        padding: 7px 11px;
      }
      .hzdot {
        display: inline-block;
        width: 9px;
        height: 9px;
        border-radius: 50%;
        margin-right: 6px;
        vertical-align: middle;
      }
      .peak {
        opacity: 0.75;
      }
      .clear-note {
        font-size: 13px;
        opacity: 0.75;
      }
      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 12px;
        border-top: 1px solid color-mix(in srgb, currentColor 25%, transparent);
        padding-top: 8px;
        font-size: 11px;
        opacity: 0.6;
      }
      .model {
        font-size: 11px;
      }
      .attribution {
        font-size: 11px;
        color: inherit;
        text-decoration: none;
      }
      /* Night flip — sage card inverts to the deep end; hazard chips flip like .wx-pin.hazard. */
      :host-context([data-theme='dark']) .briefing {
        background: var(--accent-2-900);
        color: var(--accent-2-100);
      }
      :host-context([data-theme='dark']) .hazards li {
        background: var(--accent-900);
        border-color: var(--accent-700);
        color: var(--accent-100);
      }
      :host-context([data-theme='dark']) .claim.linked {
        text-decoration-color: var(--accent-2-400);
      }
      :host-context([data-theme='dark']) .claim.linked:hover,
      :host-context([data-theme='dark']) .claim.linked:focus-visible,
      :host-context([data-theme='dark']) .more {
        color: var(--accent-2-300);
      }
      @media (prefers-color-scheme: dark) {
        :host-context(:root:not([data-theme])) .briefing {
          background: var(--accent-2-900);
          color: var(--accent-2-100);
        }
        :host-context(:root:not([data-theme])) .hazards li {
          background: var(--accent-900);
          border-color: var(--accent-700);
          color: var(--accent-100);
        }
        :host-context(:root:not([data-theme])) .claim.linked {
          text-decoration-color: var(--accent-2-400);
        }
        :host-context(:root:not([data-theme])) .claim.linked:hover,
        :host-context(:root:not([data-theme])) .claim.linked:focus-visible,
        :host-context(:root:not([data-theme])) .more {
          color: var(--accent-2-300);
        }
      }
    `,
  ],
})
export class BriefingCard {
  readonly briefing = input.required<BriefingResponse>();
  readonly units = input<'imperial' | 'metric'>('imperial');
  /** US-13 tap-to-inspect: a clicked claim's start sample index (timeline/map selection sync). */
  readonly claimSelect = output<number>();

  /** Full-text disclosure — collapses back to the brief whenever a NEW briefing arrives. */
  readonly expanded = linkedSignal<BriefingResponse, boolean>({
    source: this.briefing,
    computation: () => false,
  });

  readonly hazardCount = computed(() => this.briefing().facts.hazards.length);

  /** The two-sentence layer, only when it is genuinely shallower than the full text. */
  readonly brief = computed(() => {
    const b = this.briefing();
    return b.brief && b.brief !== b.text ? b.brief : null;
  });

  /** Claim sentences for the expanded prose — null when absent (render `text` plain instead). */
  readonly claims = computed(() => {
    const c = this.briefing().claims;
    return c?.length ? c : null;
  });

  inspect(c: ClaimModel): void {
    if (c.start_index != null) this.claimSelect.emit(c.start_index);
  }

  verdictLabel(v: Verdict): string {
    return VERDICT_LABEL[v];
  }
  color(sev: Severity): string {
    return SEVERITY_COLOR[sev];
  }
  label(sev: Severity): string {
    return SEVERITY_LABEL[sev];
  }
  dist(m: number): string {
    return formatDistance(m, this.units());
  }
}
